In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
objetivo = """
Explorar un dataset de ejemplo para entender su estructura
y generar métricas iniciales.
"""

print(objetivo)

Explorar un dataset de ejemplo para entender su estructura
y generar métricas iniciales.

In [3]:
rng = np.random.default_rng(42)

df = pd.DataFrame({
    "edad": rng.integers(18,65,100),
    "ingresos": rng.normal(2000,500,100),
    "gasto": rng.normal(1200,300,100)
})

df.head()

   edad     ingresos        gasto
0    22  2339.456782  1519.794069
1    54  2033.789535  1247.114570
2    48  2144.559699  1152.409549
3    38  2315.644113   889.303874
4    38  1271.422090   697.595117

In [4]:
print("shape:", df.shape)
df.describe()

shape: (100, 3)

             edad     ingresos        gasto
count  100.000000   100.000000   100.000000
mean    42.260000  1936.872514  1184.746035
std     12.770405   443.449663   305.393598
min     20.000000   933.976860   555.813291
25%     32.750000  1650.160135   946.279938
50%     42.000000  1893.084936  1153.328463
75%     53.250000  2231.384046  1340.724903
max     63.000000  3456.931233  1955.242211

In [5]:
kpis = {
    "edad_promedio": df["edad"].mean(),
    "ingresos_promedio": df["ingresos"].mean(),
    "gasto_promedio": df["gasto"].mean()
}

kpis

{'edad_promedio': np.float64(42.26),
 'ingresos_promedio': np.float64(1936.872513605009),
 'gasto_promedio': np.float64(1184.7460354669631)}